version: '3.9'
networks:
  tttnet:

services:
  nginx:
    profiles: ["prod"]
    image: nginx:stable-alpine
    depends_on:
      - node
    networks:
      - tttnet
    container_name: nginx_tttnet
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node:
    profiles: [ "prod" ]
    image: node:latest
    container_name: node_tttnet
    networks:
      - tttnet
    volumes:
      - ./frontend:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ './start.sh' ]
    restart: unless-stopped
  npm:
    profiles: [ "setup" ]
    image: node:12.20
    container_name: npm_tttnet
    networks:
      - tttnet
    volumes:
      - ./frontend:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm']
    user: root
    environment:
      - npm_config_cache=/var/www/html/.npmcache